### ISSUE TITLE
Documentation and kudos

### ISSUE THREAD

**Issue by nevf** [rkusa/touch-dnd#21]
First many thanks for this truly useful code. I'm working on adding touch support to an app I'm developing and as you'd be well aware, it isn't at all straightforward. I started using Sortable.js a few days ago and quickly ran into several issues, including it's use of HTML5 drag&drop which got me looking elsewhere. So far touch-dnd is working beautifully.

That said it would be extremely helpful to have documentation for all of the ```options```. Some are obvious, but others aren't. I'm sure with better documentation and an downloadable example more people would be using touch-dnd.

I'm using touch-dnd to reorder Bootstrap Tabs, which in my case are in a horizontal row. I've only had to make one small change to get this working, which is great. I also plan to use it in a tree, which hopefully will be easy to get going.

Keep up the great work and many thanks again.

**Comment by rkusa** [comment]
Thank you very much for the feedback!

http://ma.rkusa.st/touch-dnd ist an example of bad UX. The headers are actually links to, eg.: http://ma.rkusa.st/touch-dnd/sortable.html I'll improve this.

What change have you made?

**Comment by ne0d1n** [comment]
not clear how to get drop coords from example
```
$('.droppable').droppable({activeClass: 'active'})
        .on('droppable:drop', function (e, ui) { 
                // from here
        });
```

**Comment by ne0d1n** [comment]
thanks for new "Docs" links. Now mpre clear that there are links here.

**Comment by rkusa** [comment]
Which drop coords do you need? Relative to the document or to the droppable?

**Comment by ne0d1n** [comment]
relative to droppable

**Comment by rkusa** [comment]
@ne0d1n move this conversation to #22

**Comment by nevf** [comment]
@rkusa Hi Markus, you were right about the bad UX :-) The Docs are excellent. Some information worth adding is an example of the css rules for options such as ```placeholder```. I had to dig around in the example stylesheet for this.

I've made two changes so far. In my use case the ```<ul></ul>``` is empty when I call .sortable() and ```<li>```'s are added/removed later on. This meant the ```tag``` code in Sortable() did not work correctly. So I've added a new option ```placeholder_tag``` which lets me spec what this should be. ie. an ```<li>```.

````
        // Work out what tag to use for the placeholder element.
        var tag = opts.placeholder_tag
        if ( !tag )
            try {
              tag = this.el.find(this.opts.items)[0].tagName
            } catch(e) {
              tag = /^ul|ol$/i.test(this.el.tagName) ? 'li' : 'div'
            }

        this.placeholder = $('<' + tag + ' class="' + this.opts.placeholder + '" />')
````

Related to this unless I am mistaken ```this.el.tagName``` should be ```this.el[0].tagName```

The other change is in Sortable.start() to support horizontal lists where I've added a ```horizontal``` option as follows:

````
    // if dragging an item that belongs to the current list, hide it while
    // it is being dragged
    if (this.index !== null) {
      if ( this.opts.horizontal ){   // NF 18/02/2015
        var marginRight = (parseInt(dragging.el.css('margin-right'), 10) + dragging.el.width()) * -1
        dragging.css('margin-right', marginRight)
      }else{
        var marginBottom = (parseInt(dragging.el.css('margin-bottom'), 10) + dragging.el.height()) * -1
        dragging.css('margin-bottom', marginBottom)
      }
    }
````

My next challenge is to get touch-dnd working with a list which has both horizontal and vertical elements. ie. When there are more Tabs than fit in the width of the tabs parent container the remaining tabs are in a dropdown menu. In this case I want to be able to drag items to & from the horizontal & vertical lists. I think the main issue is flipping ```forcePlaceholderSize``` which I need to be true for the horizontal list, but false for the vertical list. You can see an example the Tabs code I'm using at: http://www.eyecon.ro/bootstrap-tabdrop/

I'll post back when I get this working,

Sorry about the delay replying, I wasn't working yesterday.

**Comment by nevf** [comment]
@rkusa I'm working on an update to detect whether the list is horizontal or vertical which will replace the ```horizontal```` option.

**Comment by rkusa** [comment]
Setting `margin-bottom` to a negative value should work for horizontal lists, too. But maybe only for simple use cases. So if the negative `margin-bottom` does not work for your use case, any idea which additional CSS blocks it from working?

I'll fix the tagName and add an `placeholderTag` option. Thanks for the suggestion :-)

**Comment by rkusa** [comment]
I did a fix for negative `margin-bottom` values. I've tried your code and set only `forcePlaceholderSize`. Seemed to work fine, now

**Comment by nevf** [comment]
@rkusa Thanks for the update. I see there are a lot of changes in this release. Setting ```margin-bottom``` to a negative value looks good with horizontal lists so far and is simpler than what I did. Thanks for adding ```placeholder_tag```.

I've updated the first line of ```Sortable.start()``` to only work with the left mouse button as follows:
````
    if (this.opts.disabled || dragging.el || ( event.type === 'mousedown' && e.button !== 0 ) ) return  
````

There were a couple of issues I was seeing in the previous release which appear to be fixed now. I was seeing an endless flood of  ```'sortable:update'``` events at times. I was also seeing a few of these when my app started, without any user interaction going on. These seem to be triggered by your Observer code kicking in for changes other than those made within touch-dnd. Can you confirm  these issues have been addressed?

**Comment by rkusa** [comment]
Yes the event flooding ist addressesed. If I've missed some, let me know :-)
Thanks for the left click only suggestion!

**Comment by rkusa** [comment]
Maybe I should change the code to not check for data urls specifically, but for absolute URLs (considering data urls to be absolute) and preventing the base path from being added to absolute urls, too. I'll adjust the PR tomorrow.

**Comment by nevf** [comment]
@rkusa There is a mistake in my left mouse code. Change ```event.type``` to ```e.type```. Chrome has ```window.event``` which makes this mistake not obvious.

Your _data urls_ comment is I'm afraid lost on me. :-)

**Comment by rkusa** [comment]
@nerf Oh, the data urls comment should have been for another issue in another project

**Comment by rkusa** [comment]
Thanks again for helping to improve `touch-dnd`!
