### ISSUE TITLE
Droppable Coords

### ISSUE THREAD

**Issue by rkusa** [rkusa/touch-dnd#22]
> not clear how to get drop coords from example
> $('.droppable').droppable({activeClass: 'active'})
>        .on('droppable:drop', function (e, ui) { 
>                // from here
>        });

**Comment by rkusa** [comment]
@ne0d1n Should be possible using `this.offsetTop`/`this.offsetLeft` (Position of the droppable) and `e.clientX`/`e.clientY`

**Comment by ne0d1n** [comment]
this.offsetTop & this.offsetLeft both **0**
e.clientX & e.clientY both **undefined**

**Comment by rkusa** [comment]
Ah ok, just was a guess. I'll try to propagate the original event, containing e.clientX and e.clientY properly.

**Comment by rkusa** [comment]
The event object should contain `e.offsetX` and `e.offsetY` now. These values are already relative to the droppable. Does this work for you?

**Comment by ne0d1n** [comment]
Yes, thank you for fast response!

**Comment by rkusa** [comment]
Great! :-)

**Comment by ne0d1n** [comment]
It's looks like in code below  e.offsetX and e.offsetY comes undefined for mobile devices
```javascript
.on('droppable:drop', function (e, ui) {
    var posX = e.offsetX 
}
```

**Comment by ne0d1n** [comment]
added to new issue #31
