### ISSUE TITLE
Restoring drag element styles

### ISSUE THREAD

**Issue by nevf** [rkusa/touch-dnd#23]
@rkusa Markus, I've updated Dragging.css() to resolve the issue where jQuery returns the computed style in el.css() and this is then restored in Dragging.stop() which will then override any CSS rule the element uses when there was no ```style=xyz``` value set on the element in the first place. So ``` this.el[0].style[prop] ``` tests if there is a style set and if not saves ```""``` in ```originalCss[prop]``` which will then get jQuery.css() to remove the style that was added. 

````
  Dragging.prototype.css = function(prop, val) {
    if (!this.el) return
    this.originalCss[prop] = this.el[0].style[prop] ? this.el.css(prop) : "";
    this.el.css(prop, val)
  }
````

**Comment by rkusa** [comment]
Thanks a lot!

**Comment by nevf** [comment]
Markus, as a follow on it would be nice to see all the styles you add to the drag element during a drag removed on drop etc. Less clutter in the dom etc.

**Comment by rkusa** [comment]
Good idea! Let me know if you see something I forgot to cleanup.
