### ISSUE TITLE
Before drop event

### ISSUE THREAD

**Issue by eduardev** [rkusa/touch-dnd#26]
Hi.

I know there is no before drop, so, is there any way I can prevent the draggable to be dropped (avoid the actual place in DOM) on the `droppable:drop` ?

**Comment by rkusa** [comment]
Calling `e.preventDefault()` during `droppable:drop` should now cancel the drop. Please let me know if it works for you

**Comment by eduardev** [comment]
I will test tonight, but it will certainly work ;)
Thanks @rkusa

**Comment by eduardev** [comment]
Perfect, now we can cancel drop without moving `ui.item` all together.
Thanks again @rkusa

**Comment by eduardev** [comment]
Hi @rkusa sorry, did not test it properly before. Just realized `ui.item` was not coming trough anymore.
I changed the order a bit.
Moved the `var el = dragging.el`
To before the line `var drop = trigger(this.el, 'droppable:drop', e, { item: el })`
Apparently all is good, with `e.preventDefault()` also working. The whole method is:

```php
Droppable.prototype.drop = function(e) {
    if (this.opts.disabled || !this.accept) return false

    if (!dragging.el) return
	
	// zepto <> jquery compatibility
    var el = dragging.el
    var drop = trigger(this.el, 'droppable:drop', e, { item: el })
	
    if (!drop.isDefaultPrevented()) {
      $(this.el).append(el)
    }
  }
```
Thanks

**Comment by rkusa** [comment]
Thanks a lot!
