### ISSUE TITLE
Sorting list items with nested divs pulls them apart

### ISSUE THREAD

**Issue by SeventhHelix** [rkusa/touch-dnd#27]
I'm running into an issue where trying to drag a list of bootstrap panels pulls the child divs apart instead of moving the entire panel. This results in pulling the panel-content div out of a panel and into another.

I've put together a small example of this on jsfiddle: http://jsfiddle.net/ru2bjuk9/1/
Unfortunately I'm running into security problems due to jsfiddle using different domain names so the fiddle doesn't work properly, but it's a small enough example it should be easy to reproduce. 

Any advice? I just starting using touch-dnd so I might be totally overlooking something, but I'm not sure where to go from here.

Thanks!

**Comment by rkusa** [comment]
Hi @SeventhHelix, adding the option `items: '> li'` should work. The default item selector is `li, div`. Updated example: http://jsfiddle.net/5b5apuhz/
Let me know if this works for you

**Comment by SeventhHelix** [comment]
This is exactly what I was going for! I must've missed the items option in the docs page. Thank you, @rkusa.
