### ISSUE TITLE
'ui' argument passed to sortable:activate is not object

### ISSUE THREAD

**Issue by zackd** [rkusa/touch-dnd#28]
unlike other events e.g. 'sortable:update', 'sortable:receive' the second argument passed to 'sortable:activate' is not an object.

so 
```
.on('sortable:activate', function(e, ui) {
    // ui.item.addClass('active-item'); // this fails
    $(ui).addClass('active-item'); // but this works
})
```
easy workaround, but thought it would be helpful to flag this inconsistency :)

thanks for the great plugin!

**Comment by rkusa** [comment]
This seems to be already fixed in `master`. I'll publish a new version. Thanks for reporting anyway!
