### ISSUE TITLE
Droppable only accept one draggable

### ISSUE THREAD

**Issue by zanetinemanish** [rkusa/touch-dnd#29]
Is this possible droppable accept only one item from (multiple items) draggable but droppable should not accept specific item, droppable should accept any one item from draggable.

**Comment by rkusa** [comment]
I am not sure, if I understand your use case, correctly. But maybe you are able to achieve your use case, by using a callback as the `accept` option, e.g.:

```js
$('#example-accept-function').droppable({ accept: function(el) {
  return el.hasClass('b') && ...
} })
```

**Comment by zanetinemanish** [comment]
Hello Markus, Thanks for Quick Reply :)

That is really good option but i am not sure i really want to use this option because in my case i want some function or alert on Dropping an element if already element exists.

I uploaded an Video please check : http://ph5s.com/sorting.mp4  Last option i shaking a "Answer 2" it should be undroppable and move to original position (Right Side).

Hope you understand what i want to say!

~Manish

**Comment by rkusa** [comment]
There is currently no build-in option to restrict the droppable to only accept one item. However, instead of the `accept` callback, you could also listen to the `droppable:drop` and prevent the drop it if needed, e.g.

```js
$(el).droppable().on('droppable:drop', function(e) {
  if ($(this).children().length > 0) {
    e.preventDefault() // this will prevent the actual drop
    alert("already answered") // give feedback
  }
})
```

Does this work for you?

**Comment by zanetinemanish** [comment]
Hello Markus, Thanks for Perfect Reply, You made my Day :)

~Manish

**Comment by rkusa** [comment]
You are welcome! :-)

**Comment by vieckys** [comment]
@rkusa thanks buddy. You saved my day. Thank you so much.

**Comment by vieckys** [comment]
Your plugin is awesome.
