### ISSUE TITLE
event when dragging started

### ISSUE THREAD

**Issue by ne0d1n** [rkusa/touch-dnd#30]
Not clear from doc how to add handler to start dragging event
for example to highlight dropzone.

I've tried with no success
```javascript
$(".draggable").draggable()
  .on('dragging:start', function(){
    console.log('dragging:start')
  });
```

**Comment by rkusa** [comment]
`dragging:start` is an internal event. You could use

```js
.droppable().on('droppable:activate', function() {})
```

or use the `activeClass` option of the droppable:
```js
.droppable({ activeClass: 'drop-here' })
```

Does this work for you?

**Comment by ne0d1n** [comment]
Thank you for fast answer.
droppable:activate is works perfectly.

Could you please help with some other issue,
drag proxy during dragging has bad z-index and goes under other elements.
Is any way to define drag-proxy styles?

**Comment by rkusa** [comment]
I'll add an option for this

**Comment by rkusa** [comment]
```js
.draggable({ cloneClass: 'foreground' })
```

Should work now (using `master`)

**Comment by ne0d1n** [comment]
It looks like cloneClass doen't work from current master

**Comment by rkusa** [comment]
I've added `cloneClass` to the docs: http://ma.rkusa.st/touch-dnd/draggable.html
Maybe, the example does work for you? If not, which browser are you using?

**Comment by rkusa** [comment]
I've also added `draggable:start` and `draggable:stop` events

**Comment by rkusa** [comment]
Please feel free to reopen, if the issue still exists
