### ISSUE TITLE
dropable drop postion for mobile devices

### ISSUE THREAD

**Issue by ne0d1n** [rkusa/touch-dnd#31]
It's looks like in the code below e.offsetX and e.offsetY comes undefined for mobile devices. 
For desktop browsers everything works.

```javascript
$('.droppable').droppable({activeClass: 'active'})
.on('droppable:drop', function (e, ui) {
    var posX = e.offsetX;
    var posY = e.offsetY;
    // rest code 
}
```

**Comment by rkusa** [comment]
Does the following work?

```js
var posX = window.event && window.event.changedTouches && event.changedTouches[0]. offsetX || e. offsetX
```

**Comment by ne0d1n** [comment]
It does'nt work. 

I tested it first in latest chrome (windows) in iPad emulation mode, 
and additionally checked in safary ipad and chrome android.

window.event.changedTouches does have values for screenX, clientX but not offsetX 
(in windows chrome iPad emulation mode)

**Comment by rkusa** [comment]
`touch-dnd` uses this code snippet internally to get `pageX` and `pageY` across devises. However, I don't know how to get `offsetX` / `offsetY` across all devices and `touch-dnd` does not set them on `droppable:drop`. This event is actually a forwarded `mouseup` (or `touchend MSPointerUp pointerup`).

You probably have to calculate them on your own using e.g. `pageX` and the elements `offsetLeft`?

**Comment by ne0d1n** [comment]
worked with
```javascript
var posX = window.event.changedTouches && window.event.changedTouches[0].pageX - $("#c").offset().left || e.offsetX;
```
thanks

**Comment by rkusa** [comment]
:+1:
