### ISSUE TITLE
Possible to create flipping between dropped elements

### ISSUE THREAD

**Issue by zanetinemanish** [rkusa/touch-dnd#32]
Hello again Markus, 

Today i am creating another template an issue comes front of me, can you please help me, as previously.

In template user can interchange the dropped elements as you see in a video what i want to do. If user can drop 1'st element to 2'nd dropped element then 2'nd element can change it's position with first one.

Video : http://ph5s.com/video2.mp4
~Manish

**Comment by rkusa** [comment]
I've added the `receiveHandler` option for droppable today. Maybe this comes in handy here.

E.g.:

```js
$().droppable({
  receiveHandler: function(ui) {
    if ($(this).children().length > 0) {
      // swap
    }
  }
})
```

**Comment by rkusa** [comment]
Did this work for you?

**Comment by zanetinemanish** [comment]
Nope!

**Comment by rkusa** [comment]
Nope? Did you get an error?

**Comment by zanetinemanish** [comment]
Can you give a little example about it like previous one?

**Comment by rkusa** [comment]
Again, quickly written down and untested:

```js
$().droppable({
  receiveHandler: function(ui) {
    if ($(this).children().length > 0) {
      ui.item.parent().append($(this).children().first())
      $(this).append(ui.item)
    }
  }
})
```

**Comment by zanetinemanish** [comment]
Thanks again for your quick response.
Hadnler function code for swap/interchange the element.

Please see video again what i need.  http://ph5s.com/video1.mp4
When Right side element we drop on left side(one Image's bubble) on droppable element. Droping any (bubble) element on wrong place on left side (one Image's bubble) we should able to interchange there location such as in video dropping all element on left side we need to interchange like number(4) bubble dragging on number(1) swap/interchange or both number change there positions number(4) take position number(1) and number(1) take position number(4). Like other numbers(bubbles) should change there position. swap/interchange function only apply able on left side. Swap/Interchange function should not work on right side.

**Comment by rkusa** [comment]
A combination of those both should do the trick:
http://codepen.io/anon/pen/waMaOy?editors=101
http://codepen.io/anon/pen/eNzXOK?editors=101
