### ISSUE TITLE
Drop on it's own position

### ISSUE THREAD

**Issue by zanetinemanish** [rkusa/touch-dnd#33]
Hi, I have an another issue, in this video i want to drop each element on it's own dragged position.

User cannot interchange with draggable elements but in dropped elements.

Video : http://ph5s.com/video1.mp4

~Manish

**Comment by rkusa** [comment]
Sorry I don't get your issue. The things you do in the video seems to work fine. Which part does not work? Maybe give the second of the video

**Comment by zanetinemanish** [comment]
Hello Markus, I am sorry for not more explanation you correctly, I am too close on issue, please start Video from 0:13 when all elements on left side. user cannot drop any element on others like
as i want : 
1-1
2-2
3-3
4-4
not as :
1-3
2-4
3-1
4-2
Hopefully you recognize my issue.

~Manish

**Comment by zanetinemanish** [comment]
I didn't get the console, Is any event in plugin that we find html of drag element on dropping.

.on('droppable:drop', function(e){
       var dragging_handler = $(this).find('.sort-drag').data('number');
       var droppable_handler = $(this).find('.sort-overlay').data('number');

       // I didn't get the console
       console.log(dragging_handler);
       if( dragging_handler != droppable_handler) {
         e.preventDefault();
       }
   });

**Comment by rkusa** [comment]
```js
.on('droppable:drop`, function(e, ui) {
  console.log(ui.item)
})
```

If I get you right, you try to achieve the following: http://codepen.io/anon/pen/waMaOy ?

**Comment by zanetinemanish** [comment]
Great you did well that's impressive :+1:
