### ISSUE TITLE
Drag Multiple items

### ISSUE THREAD

**Issue by zanetinemanish** [rkusa/touch-dnd#34]
Is this possible that user select two items for droppable, means to say that user have to select first item and then second item and then user drag both items into droppable element.

**Comment by rkusa** [comment]
This is not implemented. However, maybe extending the draggable `clone` option to accept a function, which returns the clone/helper to be used, is enough to support this feature.

Workflow would be:
1. custom logic to mark draggables as selected
2. create a dragging clone/helper that reflects either one draggable or multiple draggables
3. custom droppable `receiveHandler` that adds all selected items

Could this work for you?

**Comment by zanetinemanish** [comment]
Can you give a little example about it?

**Comment by rkusa** [comment]
Just a quick untested sketch (expects current master):

```js
$('.draggable').click(function() {
  $(this).toggleClass('selected')
})

$('.draggable').draggable({
  clone: function() {
    $(this).addClass('selected')

    var selected = $('.draggable.selected')
    if (selected.length == 0) {
      return this
    } else {
      return $('<div>' + selected.length + ' elements</div>')
    }
  }
})

$('.droppable').droppable({
  receiveHandler: function(ui) {
    var droppable = this
    $('.draggable.selected').each(function(el) {
      el.removeClass('selected')
      droppable.append(el)
    })
  }
})
```

**Comment by zanetinemanish** [comment]
Hello Markus, 

Yes  you did well but i got some error, i improve some little change in droppable, hope it will be helpful :+1: 

$('.droppable').droppable({
  receiveHandler: function(ui) {
    var droppable = $(this);
    $('.draggable.selected').each(function() {
      droppable.append($('.draggable.selected'))
    })
    $('.draggable.selected').removeClass('selected');
  }
});

**Comment by rkusa** [comment]
Great! :+1:
