### ISSUE TITLE
Sortable : Active Class 

### ISSUE THREAD

**Issue by sahibsingh** [rkusa/touch-dnd#35]
Hello Markus,

I am too impressed with your plugin, but can you please guide me how to add .Activeclass to single item on sortable.

~Sahib

**Comment by sahibsingh** [comment]
$('.sequence').sortable({forcePlaceholderSize: true, activeClass: 'active'});

but i want to add Class to an Single draggable item not to parent.

Thanks & Regards
Sahib

**Comment by rkusa** [comment]
Hi @sahibsingh, you could try something like:

```js
.sortable()
.on('sortable:start', function(e, ui) { ui.item.addClass('active') })
.on('sortable:stop', function(e, ui) { ui.item.removeClass('active') })
```

Does this work for you?

**Comment by sahibsingh** [comment]
Thanks @rkusa  you solved it. Great :+1:

**Comment by sahibsingh** [comment]
Can we do this thing same as with Dragging and Dropping?
