### ISSUE TITLE
Click events not working on iPad

### ISSUE THREAD

**Issue by sahibsingh** [rkusa/touch-dnd#36]
Hello @rkusa  again, I am trying your plugin with bootstrap modal window, I want to drag a modal window, Everything is fine but when modal window is opened none of anchor works properly.

Here is demo : http://jsfiddle.net/indianwebdesigner/csuscr9v/3/

~Sahib

**Comment by rkusa** [comment]
Thanks for reporting! I'll look into it at the weekend

**Comment by sahibsingh** [comment]
Yes Sure! take your time :)

**Comment by rkusa** [comment]
What do you mean with "anchor"? There are no HTML anchors, so you probably mean something else?

**Comment by sahibsingh** [comment]
mean to say like close buttton not working if i added new anchor then it also not working on iPad

**Comment by rkusa** [comment]
The close button should work now. I still don't geht the anchor part. Could you update your example to show your anchor issue?
