### ISSUE TITLE
Sorting applied to all child elements, not the accepted ones, on dynamically generated items

### ISSUE THREAD

**Issue by mydudechris** [rkusa/touch-dnd#37]
I'm pulling data from a json file via a simple ajax call and rendering a list on a page.
I call a function that runs at the end of the list generation that includes 

    function enableDnD () {
        $('.alert_list').sortable({ accept: 'div'});
    }

Here is what my list looks like before I attempt to sort:

http://cl.ly/image/2U2V1g263m07

The drag/sort goes crazy when I attempt to drag items. If I select the date, it grabs just the date, or if I grab the paragraph, just the paragraph. My expectation is that it will grab the parent div that includes all of it. This is probably best explained with a video:

http://cl.ly/062h2V162F03

Maybe I'm missing something but this seems strange.

**Comment by mydudechris** [comment]
Also, what would cause my element to sit behind the other elements on drag? Shouldn't it be sitting above or is that controlled with css classes that we're supposed to define ourselves?

**Comment by mydudechris** [comment]
Hmmm, it looks like it might be my html structure which is really strange as it's valid HTML5. If I change the display: flex, which I'm using to vertically align content, to an undeclared value display: '' then it kinda works.

**Comment by mydudechris** [comment]
Sorry for blowing this up!

**Comment by rkusa** [comment]
If you want it to apply only to the top-level elements you have to use the respective CSS selector, eg: `{ items: '> li' }`
