### ISSUE TITLE
Restore iFrame compatibility

### ISSUE THREAD

**Issue by rkusa** [rkusa/touch-dnd#4]
[ma.rkusa.st/touch-dnd/example.html](http://ma.rkusa.st/touch-dnd/example.html)

**Comment by janegbert** [comment]
I'm on the horns of a dilemma here. Zepto DND does not handle scrolling where Touch DND does. Touch DND on the other hand does not support cross-frame which Zepto DND does. The cross-frame support is what got me into Zepto DND in the first place. Any chance of this issue being reopened / reconsidered?

**Comment by rkusa** [comment]
Hi @janegbert. I am sorry, I don't have the resources to work on cross-frame support for touch-dnd, since it is a lot of work and I personally don't have a use case for it. I'll have a look at scrolling for zepto-dnd instead.

**Comment by rkusa** [comment]
Found some time to add at least basic iframe support, ie., support for dragging things into iframes (not out of a iframe).

branch: [iframe](https://github.com/rkusa/touch-dnd/tree/iframe)
example: http://ma.rkusa.st/touch-dnd/example.html

**Comment by janegbert** [comment]
It works! Although scrolling, which works fine in other Touch DND examples, has some strange behaviour. As I am dragging and using the scroll wheel at the same time the draggable scrolls along with the page instead of "sticking" to the cursor.

**Comment by rkusa** [comment]
Thanks for having a look. I'll fix the scroll wheel issue

**Comment by rkusa** [comment]
@janegbert For which draggable, the one in the main or the one in the iframe window? And, which browser?  Thanks!

**Comment by janegbert** [comment]
The draggable in the main window has this issue. The sortables in the iframe are scrolling fine.

**Comment by rkusa** [comment]
Should work now, would you mind having a look? Thanks

**Comment by janegbert** [comment]
Sorry for not getting back to you on this issue. It's solved! Thanks!
