### ISSUE TITLE
Elements flicker like crazy when one is smaller than another

### ISSUE THREAD

**Issue by mydudechris** [rkusa/touch-dnd#41]
### Issue
When dragging elements that are smaller, such as half height, to elements that are larger you get a crazy flicker effect. This isn't as noticeable if you move things quickly but is very noticeable if you move one up or down.

### Video
http://cl.ly/1p442T2Z1z1M

**Comment by rkusa** [comment]
I've improved the behaviour. However, it is not completely fixed yet. If you slowly move the element to the left bottom, the flicker still occurs, but I am not yet sure how to fix this

Thanks for reporting!
