### ISSUE TITLE
touch-dnd.js:674 Uncaught TypeError: $.proxy is not a function

### ISSUE THREAD

**Issue by hiracse091** [rkusa/touch-dnd#43]
I have included zepto.js
My html are
 <div class="mainField">
          <ul class="field_row" >
                 <li class="fw">item 1</li>
                 <li class="fw">item 2</li>
                 <li class="fw">item 3</li>                 
           </ul>
            <ul class="field_row">
                  <li class="fw">item 4</li>
                  <li class="fw"> item 5</li>
                  <li class="fw">item 6</li>
                  <li class="fw">item 7</li>
            </ul>
</div
javascript:
$('.field_row').sortable({});

but i am getting this error:
Uncaught TypeError: $.proxy is not a function @ touch-dnd.js:674

**Comment by hiracse091** [comment]
I solved this by  replacing my zepto with yoour example zepto

**Comment by rkusa** [comment]
Hi, Zepto is split into modules: http://zeptojs.com/#modules
The $.proxy error suggests that you were missing the `event` module. zepto-dnd also requires the data module (besides the default ones)
