### ISSUE TITLE
Events "draggable:start" and "draggable:stop" not working as documented

### ISSUE THREAD

**Issue by kokoon** [rkusa/touch-dnd#46]
The draggable events listed on the bottom of [documentation page for draggable](http://ma.rkusa.st/touch-dnd/draggable.html) are not being triggered.

What is being triggered instead, is `"dragging:start"` and `"dragging:stop"`, but only on the `this.eventHandler` element, which isn't in the DOM. What is the correct way to make use of these events?

**Comment by kokoon** [comment]
Turns out npm served me an older version of the library, maybe that needs to be updated?

**Comment by rkusa** [comment]
Thanks for pointing this out. I've published `1.1.0` now
