### ISSUE TITLE
Event "draggable:stop" gets triggered for all draggables instead for only current one

### ISSUE THREAD

**Issue by kokoon** [rkusa/touch-dnd#47]
At the moment, I'm using a workaround in the handler function:
```
if (ui.item[0] != e.target) return;
```

I don't think this is a correct behavior.

**Comment by rkusa** [comment]
You are right, that is not a correct behavior. Thanks for reporting! I'll fix it soon

**Comment by rkusa** [comment]
Should be fixed in `master` branch. Thanks again for reporting!
