### ISSUE TITLE
Droppable hoverClass turns off when hovering an element nested inside of it

### ISSUE THREAD

**Issue by kokoon** [rkusa/touch-dnd#49]
I believe this is an incorrect behavior, it can be tested on http://ma.rkusa.st/touch-dnd/.
Drop one of the draggable boxes in the droppable box, then grab another one and carry it over the little box inside the droppable - the hover effect disappears.

Since dropping the draggable there works, I believe the `hoverClass` should not go away when hovering a nested element.

**Comment by rkusa** [comment]
Thanks, should be fixed
