### ISSUE TITLE
Draggable+clone+sortable

### ISSUE THREAD

**Issue by calebelt** [rkusa/touch-dnd#52]
The problem is this: left panel - a list of tasks, right panel - the calendar. The list of tasks can be sorted. Calendars can also be sorted. The user picks an element from the left panel, drag tasks to the calendar. It is important that the user gets clone task element and in the left panel the element remains.
How to do it?

**Comment by rkusa** [comment]
Maybe the sortable `receiveHandler` option does work for you? E.g. http://codepen.io/rkusa/pen/VvqwPM

**Comment by calebelt** [comment]
rkusa thanks, but this standard code. In the example of a link is no sorting of items "d" and "e". How to do the same, but with a sort of "d" and "e"?

**Comment by rkusa** [comment]
Use sortable instead of draggable for `d` and `e`: http://codepen.io/rkusa/pen/LpMYjj

**Comment by calebelt** [comment]
rkusa thank you very much! I did not know what to do just sortable (), thought to do draggable().sortable()

**Comment by rkusa** [comment]
You are welcome

**Comment by calebelt** [comment]
Maybe someone will need this example.
I added the option "placeholderHeight", to make a comfortable sorting tree.
http://codepen.io/calebelt/pen/GpPpQX

**Comment by rkusa** [comment]
:+1:
