### ISSUE TITLE
Double click, animation return

### ISSUE THREAD

**Issue by calebelt** [rkusa/touch-dnd#53]
Hi! 
1. How to add an event, double-click on the element to be sorted?
2. How to remove the animation element returns after releasing the mouse button?
http://webismy.work/cms/dnd/dnd.html

**Comment by rkusa** [comment]
> How to add an event, double-click on the element to be sorted?

Could you explain this in more detail? I don't see how double-click should work in conjunction with drag and drop?

> How to remove the animation element returns after releasing the mouse button?

Add the following CSS rule for the corresponding elements:

```css
transition: none !important;
```

**Comment by calebelt** [comment]
Sorry for the long answer - it was a lot of work.
I want to do so that would be a double-click on the menu item opens the editing window of the unit. Each menu item is a unit that can be added to the template. These blocks can be edited in a template using ContentTools or in a modal window.

**Comment by rkusa** [comment]
Dblclick is not within the scope of touch-dnd. Does `.on('dblclick', function() {})` not work? Or do you get a weird behaviour in combination with touch-dnd?

**Comment by calebelt** [comment]
Do not operate a mouse event on sortruemyh elements.
https://github.com/calebelt/kubiki-cms/blob/master/dnd.html#L127
And test: http://webismy.work/cms/dnd/dnd.html

**Comment by rkusa** [comment]
When using the `handle` option, dblclick works fine: http://codepen.io/anon/pen/vLBBrd?editors=101

**Comment by calebelt** [comment]
I read your documentation about handle. I wanted to do without any additional buttons. So I make a button for each item. 
Thanks for the answer!

**Comment by rkusa** [comment]
You are welcome
