### ISSUE TITLE
Events won't fire and drag elements don't respond to touch

### ISSUE THREAD

**Issue by JustinEldracher** [rkusa/touch-dnd#54]
Hi, I'm having a rather frustrating problem here.

I'm trying to make it so the client can drag certain rows in a table around to sort them numerically, and then once they are done sorting I need to be able to get the order of the sorted elements so I can AJAX them to the server and update the database.

I've got my initialization code set up like this:

```javascript
$(".table-sortable").sortable({
	accept: ".drag",
	forcePlaceholderSize: true,
	items: "tr.drag",
	handle: ".drag-handle"
}).on("sortable:update", function(event, ui) {
	alert("hi!");
});
```

The table rows with the class `.drag` are indeed sortable and that much works great, the only problem is that I never get that "hi!" alert.  I've been using the documentation at http://www.jqueryrain.com/?ovZdy1dF but I can't seem to get anywhere.

And then when I try to drag things by touch, nothing happens.

What am I doing wrong?

**Comment by rkusa** [comment]
Hi, your code seems to work fine: http://codepen.io/rkusa/pen/mVwxvq?editors=101
If this does not work for you, which browser are you using?

However, `touch-dnd` hides/collapses the currently dragged element using a negative `margin-bottom`. This unfortunately does not work for `tr` elements. As long as you are fine with having some whitespace where the dragged element comes for, this is not a problem. If you don't like this whitespace, I am afraid `touch-dnd` is not a good fit for your use case.

**Comment by JustinEldracher** [comment]
Yeah, the drag method works fine, so that's not an issue.

Yeah, the pen works just great.  I'm using it in a project with bootstrap and a whole bunch of other javascript, so I'm thinking I must have a conflict somewhere.  I don't need the Zepto.js library, do I?

Thanks for your help, and I'll let you know what is causing the problem, once I figure it out... :wink:

**Comment by rkusa** [comment]
Yes you don't. Zeptojs could be used as a replacement for jquery. Do you get the "Hi!" alert in the  codepen example above, but you don't get the alert in your project?

**Comment by JustinEldracher** [comment]
OK, that's what I thought.

I'm using Google Chrome, the code pen works great, I get the alert and it responds to touch, but the only thing that works in my project is the mouse dragging and the methods like $(".tabe-sortable

**Comment by rkusa** [comment]
Yes, sounds like some kind of conflict between different JS libraries. If you are able to reproduce it in a minimal example, I could take a look.

**Comment by JustinEldracher** [comment]
It's a complicated administrative control area, so I couldn't really reproduce it very easily.

I'm using jQuery (obviously), jQuery UI, bootstrap, and then a few more jQuery plugins.

**Comment by rkusa** [comment]
Sorry for the late answer. It really sounds like inferences between plugins, e.g, some plugin preventing the propagation of an event. That is, I am not able to help out :-/

**Comment by JustinEldracher** [comment]
That's fine, I've had to put it on the back burner for a while anyway, but I'll let you know when I get it figured out.

**Comment by JustinEldracher** [comment]
OK, jQuery UI turns out to be the culprit!  I removed it from the project because I decided to use other plugins instead, and presto!  I could drag & drop with touch and all the events fired like they're supposed to! :)
