### ISSUE TITLE
Combination of jquery 1.12.4 and jquery-migrate 1.4.1 causes error.

### ISSUE THREAD

**Issue by christianmagill** [rkusa/touch-dnd#64]
When using jQuery 1.12.4 and jQuery Migrate 1.4.1 as is standard in WordPress I am coming across the following error on drag.

touch-dnd.js:59 Uncaught TypeError: Cannot read property 'Event' of undefined

The relevant line:

`var e = win.$.Event(name, props)`

Any ideas?

**Comment by rkusa** [comment]
Thanks for reporting! A fix is published as `1.1.3`. Please let me know if it still not works

**Comment by christianmagill** [comment]
That fixed it. Thanks!

**Comment by rkusa** [comment]
You are welcome
