### ISSUE TITLE
touch-dnd is not compatible with module loaders and TypeScript

### ISSUE THREAD

**Issue by heartdisease** [rkusa/touch-dnd#74]
I am using touch-dnd in a small pet project that was originally written in plain JavaScript and that I've just recently converted into a TypeScript project (no Angular etc., just plain TypeScript). That's when I realized that touch-dnd does not work with currently used module loaders (AMD, UMD, System.js, ...) which automatically makes it pretty unusable in a TypeScript project. The only way I got it running was by lazy-loading the touch-dnd plugin after setting the window.jQuery global variable first (which is pretty much what you don't want when you're working with modules).

In pull request #73 I have therefore made it compatible with common module loaders so that it does not necessarily depend on global state. To also make it usable with TypeScript, I've also added a (hopefully) complete type definition file that the transpiler can use.

I understand that this repo is marked as unmaintained and that JQuery is not exactly the coolest library on the block these days, but your plug-in is very easy to use and still works very well on both desktop systems and mobile devices (which is my primary use case). I've already tried `interact.js`, but that didn't really work out for me; it might be more powerful but also more complicated to use and I couldn't get it to work with TypeScript either (at least not without some modifications to its code).

Most of the work is already done, you'd just have to take a quick look at the pull request and merge it. I would much appreciate it if the npm package could be updated with these changes as well so other developers can use touch-dnd in modern JavaScript/TypeScript projects as well.

**Comment by rkusa** [comment]
Hi, I appreciate your effort! PR looks good. I've merged it and published 1.2.0.
