### ISSUE TITLE
README.md and CHANGELOG.md are out of date

### ISSUE THREAD

**Issue by heartdisease** [rkusa/touch-dnd#76]
The changelog for version 1.2.0 is still missing and copyright note in README.md still says 2013-2015 instead of 2018.

All this was fixed in pull request  #75, so I hereby request it being merged back into the repository.

More importantly, I want to use this pull request/issue to ask for the NPM repository at https://www.npmjs.com/package/touch-dnd to be updated to the current version 1.2.0.
The latest version that can currently be installed using NPM is 1.1.3, which is already 2 years old and lacks support for TypeScript and module loaders like require.js. The version badge that is rendered in README.md also still shows version 1.1.3 because of that.

It might also be a good idea to update the tag for version 1.2.0 after this PR has been merged, but I think that updating the NPM repo is most important.

**Comment by rkusa** [comment]
All valid suggestions! 👍 I've published `1.2.0`, but also `1.2.1` which includes the minified script versions (`prepublish` scripts had been deprecated since the last time I did a NPM release for `touch-dnd` 🙈).

Thanks for pushing me to keep `touch-dnd` alive 😉
