### ISSUE TITLE
Compatibility with Windows 8, Surface, Surface RT

### ISSUE THREAD

**Issue by rkusa** [rkusa/touch-dnd#8]

**Comment by michael-whelan** [comment]
Is this still the case

**Comment by rkusa** [comment]
Should be fixed in `master`. Did a remote connection from my iPad to a PC. I hope, this fix works for Surface, too.

**Comment by michael-whelan** [comment]
My problem has been that 
	canvas.addEventListener("touchstart",touchStart,false);
	canvas.addEventListener("touchmove",touchMove,false);
	canvas.addEventListener("touchend",touchEnd,false);
doesn't fire on touch.
I found:
    canvas.addEventListener("MSGestureStart", touchStart, false);
    canvas.addEventListener("MSGestureEnd", touchEnd, false);
    canvas.addEventListener("MSGestureChange", touchMove, false);
but the same result. It never fires.

**Comment by rkusa** [comment]
These are the events I am using. I think either ` MSPointerDown` or  `pointerdown` was working for IE

```js
var START_EVENT = 'mousedown touchstart MSPointerDown pointerdown'
    , END_EVENT   = 'mouseup touchend MSPointerUp pointerup'
    , MOVE_EVENT  = 'mousemove touchmove MSPointerMove pointermove scroll'
```
